name: school_management_system
description: "App for managing school activities"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hugeicons: ^0.0.7
  fl_chart: ^0.69.2
  google_nav_bar: ^5.0.7
  intl: ^0.20.1
  flutter_svg: ^1.1.6
  dropdown_button2: ^2.3.9
  supabase_flutter: ^2.0.0
  shimmer: ^3.0.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_file: ^3.3.2
  flutter_pdfview: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800